package com.example.cristiannavarrete.my_shopping;

import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;

import org.w3c.dom.Text;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;

/**
 * This is the class that will show the seller the
 * revenue generated by each product and the total
 * final revenue.
 * Created by Cristian Navarrete on 11/30/2015.
 */
public class FinancesPage extends AppCompatActivity {

    Button goBack;
    TextView revenueTV;
    private MyDBHandler db;
    private Singleton instance = Singleton.getInstance();
    private ArrayList<Product> products = new ArrayList<>();
    int rows;
    double totalRevenue = 0.00;

    /**
     * This function is called when a new activty of this class is created.
     *
     * @param savedInstanceState Bundle containing data from a previous instance
     *                           of an activity
     */
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.finances_page);

        LinearLayout l = (LinearLayout) findViewById(R.id.financesScroll);
        goBack = (Button) findViewById(R.id.financesGoBack);
        revenueTV = (TextView) findViewById(R.id.totalRevenue);

        db = new MyDBHandler(this, null, null, 4);

        rows = db.numRowsOfSeller(instance.getUserName());

        for (int i = 0; i <= rows - 1; i++) {
            Product productToAdd;
            productToAdd = db.getRowProductDataOfSeller(i, instance.getUserName());
            products.add(productToAdd);
        }

        for (int i = 0; i < products.size(); i++) {

            TextView tvName = new TextView(this);
            TextView revenueTV = new TextView(this);
            TextView totalSoldTV = new TextView(this);

            totalRevenue += db.getProductRevenueById(products.get(i).getId());
            tvName.setText(products.get(i).getName());
            tvName.setPadding(0, 35, 0, 0);
            tvName.setTextSize(25);
            tvName.setTextColor(Color.BLACK);
            revenueTV.setText("Revenue: $ " + Double.toString(round(db.getProductRevenueById(products.get(i).getId()), 2)));
            revenueTV.setTextSize(20);
            totalSoldTV.setText("Total Sold: " + Integer.toString(db.getTotalAmountSoldById(products.get(i).getId())));
            totalSoldTV.setTextSize(20);

            l.addView(tvName);
            l.addView(revenueTV);
            l.addView(totalSoldTV);

        }

        revenueTV.setText("Total: $" + Double.toString(round(totalRevenue, 2)));

        goBack.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent k = new Intent(FinancesPage.this, SellerMainPage.class);
                startActivity(k);
            }
        });
    }

    public static double round(double value, int places) {
        if (places < 0) throw new IllegalArgumentException();

        BigDecimal bd = new BigDecimal(value);
        bd = bd.setScale(places, RoundingMode.HALF_UP);
        return bd.doubleValue();
    }

    /**
     * Used to override the back button of the android device
     * to do nothing.
     */
    @Override
    public void onBackPressed() {return;}
}
